### PR TITLE
added connection between createRoom and backend

### PR DESCRIPTION
**Pull request by tretyakovalex**
This pull request relies on the backend api from this pull request by Andy (https://github.com/The-Creative-Programming-Group/sketchit-challenge/pull/10).

### CODE REVIEW

**Review by tretyakovalex — COMMENTED** [review]
added connection between createRoom and the backend api.

**Comment by FleetAdmiralJakob** [comment]
@tretyakovalex Cab you fix the merge conflicts
image

**Comment by tretyakovalex** [comment]
I resolved the conflicts, but for some reason it says that they are not resolved:

image

**Comment by FleetAdmiralJakob** [comment]
@tretyakovalex I can't merge it without that these conflicts are solved

**Pull request closed without merging**
